/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("geoprojekt.kotlin-library-conventions")
}

dependencies {
  //api(project(":db"))
  implementation("com.google.code.gson:gson:2.8.6")
}
