/*
 * This file was generated by the Gradle 'init' task.
 */

val javaVersion = "11"
val ktorVersion = "1.5.0"

plugins {
    id("geoprojekt.kotlin-application-conventions")
}

dependencies {
    implementation(project(":utilities"))
    implementation(project(":db"))
    implementation("io.ktor:ktor-server-core:${ktorVersion}")
    implementation("io.ktor:ktor-server-netty:${ktorVersion}")
    implementation("io.ktor:ktor-gson:${ktorVersion}")
}

application {
    // Define the main class for the application.
    mainClass.set("geoprojekt.app.AppKt")
}

val compileKotlin: org.jetbrains.kotlin.gradle.tasks.KotlinCompile by tasks
compileKotlin.kotlinOptions.jvmTarget = javaVersion
