/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package geoprojekt.app

class MessageUtils {
    companion object {
      fun getMessage(): String = "Hello      World!"
      fun getMessage(nev:String): String = "Hello      $nev!"
    }
}
