/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("geoprojekt.kotlin-library-conventions")
}

dependencies(
{
  implementation(project(":utilities"))
  implementation("org.jooq:jooq:3.14.4")
  implementation("com.zaxxer:HikariCP:3.4.5")
  implementation("org.postgresql:postgresql:42.2.18")
  //implementation("com.google.code.gson:gson:2.8.6")
}           )
